server:
  port: 7004
  
spring:
  application:
    name: CLOUD-CONFIG-SERVER
    
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RajeevPal458/codingInterviewPreparation/
          clone-on-start: true

    
    