server:
  port: 7171
  
spring:
  application:
    name: API-GATEWAY
      
      
zuul:
# service will be mapped under the '/api'  base uri
  prefix: /api
  routes:
    DepartmentMicroService:
      path: /departmentService/**
     # url: http://localhost:7001/department  or
      serviceId: DEPARTMENT-SERVICE
    UserMicroService:
      path: /usersService/**
     # url: http://localhost:7002/users/  or
      serviceId: USER-SERVICE
                    
            
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            
            
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
    
           

    